baseURL = "https://adhithya.ml/"
title = "That Simple Electrical Engineer"
author = "Adhithya"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "hugo-casper3"
 
[params]
  mainSections = ["post"]
[menu]
  [[menu.main]]
    identifier = "Devices"
    name = "Devices"
    url = "/categories/EDC/"
    weight = 1
  [[menu.main]]
    identifier = "Machines"
    name = "Machines"
    url = "/categories/EM/"
    weight = 3
[[menu.main]]
  identifier = "EMT"
  name = "EMT"
  url = "/categories/EMT/"
  weight = 2
[[menu.main]]
  identifier = "Maths"
  name = "Maths"
  url = "/categories/MATHS/"
  weight = 4
#[[menu.main]]
#  identifier = "Data structures"
#  name = "Data structures"
#  url = "/categories/DSA/"
#  weight = 5